export const ADD_SOME = 'ADD_SOME';
export const MINUS_SOME = 'MINUS_SOME';
export const SET_MOVIES = 'SET_MOVIES';
export const SET_TWEETS_QUERY_FIELD='SET_TWEETS_QUERY_FIELD';
export const SET_TWEETS_QUERY_OPERATOR='SET_TWEETS_QUERY_OPERATOR';
export const SET_TWEETS_QUERY_VALUE='SET_TWEETS_QUERY_VALUE';
export const SET_TWEETS='SET_TWEETS';
export const CLEAR_TWEETS='CLEAR_TWEETS';
export const RELOAD_TWEETS='RELOAD_TWEETS';

